-- AlterTable
ALTER TABLE "Card" ADD COLUMN     "lapses" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "state" TEXT NOT NULL DEFAULT 'new',
ALTER COLUMN "interval" SET DEFAULT 0,
ALTER COLUMN "interval" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "ReviewLog" ADD COLUMN     "lapses" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "state" TEXT NOT NULL DEFAULT 'review',
ADD COLUMN     "timeSpentMs" INTEGER,
ALTER COLUMN "interval" SET DATA TYPE DOUBLE PRECISION;
