// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// In Prisma 7 the datasource URL lives here, not in schema.prisma.
//
// Supabase gives you two URLs:
//   DATABASE_URL  — pooler URL (port 6543, ?pgbouncer=true) — used by the app at runtime
//   DIRECT_URL    — direct URL (port 5432)                  — used here for migrations
//
// The Prisma CLI (migrate dev / db push) uses datasource.url below.
// The app runtime uses DATABASE_URL via @prisma/adapter-pg in server/src/lib/prisma.ts.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use the direct connection for migrations so they bypass PgBouncer.
    url: process.env["DIRECT_URL"],
  },
});
